logging:
    level:
        blog: WARN
        org: WARN
        org.hibernate.SQL: DEBUG
server:
    port: 8000
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/softuni-mobilele?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: false
                show_sql: false
