spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/pizzaShop?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
        username: root
#        for deployment
#        url: jdbc:mysql://lb-db.mysql.database.azure.com:3306/pizzaShop?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
#    username: cnb'@'20.246.228.176 #manager
#    password: ${DB_PASSWORD} #Dancho.10
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    servlet:
        multipart:
            max-file-size: 1MB
            max-request-size: 5MB
    sql:
        init:
            mode: never
    security:
        user:
            name: "manager"
            password: "manager"

